### ISSUE TITLE
Question: What is the status and future of this plugin?

### ISSUE THREAD

**Issue by kreczko** [UW-Madison-HEP/xrootd-hdfs#39]
Hi all,

Seeing as this plugin is no longer part of the OSG documentation, I assume it is being phased out.

Are there any plans regarding
 - future developments
 - archiving this repo
 - talks with the [xrootd team](https://github.com/xrootd) to change ownership?

If there are no plans: Could you please add a `LICENSE` to make clear if future modification/forks are allowed?

**Comment by djw8605** [comment]
Added license in #40

**Comment by bbockelm** [comment]
Good call on the LICENSE file!  Definitely an oversight.

The support from OSG is indeed being phased out; currently, our official end-of-support date is February 2022.

I'm not sure we have really thought through what it means for the repository, however.  I'd like to keep it available for folks who need it (or even want to do some minor maintenance and whatnot).  If that is under the OSG organization umbrella and we invite some outside collaborators, that's fine with me.  If there's a good alternate home (xrootd sounds fine; would welcome other ideas) and it improves the experience - that's fine too!

After all, it lived under my personal account for the first ~5 years or so.  Can't hurt it to move once again.

@kreczko - your thoughts?

**Comment by kreczko** [comment]
If there is some planned (unofficial?) effort to continue on this, then the current location is fine.
Should there be interest and funded effort from the xrootd side (I do not have any contact to the team), then it might be better there (like `xrootd-ceph`).

But either way, now that there is a fairly generous license, I can also make changes in my [local fork](https://github.com/uobdic/xrootd-hdfs/tree/kreczko-hdfs3-debug) (like the user mapping customization).

If there is someone who is willing to review PRs in the future, then I can also try to contribute back in case any future changes are deemed interesting.
Fun fact: after a bit of debugging it turns out that the plugin works well with xrootd 5.3 and HDFS 3.3.1 in case any T2 might want to upgrade.

**Comment by PerilousApricot** [comment]
@kreczko was looking through this repo and noticed this comment. The repo is moved to the UW Madison repo and still being actively used, if that helps update.
